images/dash0-instrumentation/Dockerfile, images/dash0-instrumentation/node.js/.gitignore, images/dash0-instrumentation/node.js/build.sh, images/dash0-instrumentation/node.js/package.json, internal/removal/operator_pre_delete_handler.go, internal/webhook/dash0_webhook_test.go, internal/workloads/workload_modifier.go, internal/workloads/workload_modifier_test.go, test-resources/bin/test-cleanup.sh, test/util/resources.go, test/util/verification.go
Also:
* load Node.js distribution via package name instead of individual source file in --require parameter
* do not call bin/pack but just npm pack when rebuilding the Node.js distribution
=> chore(instrumentation image): update node distro repo & package name

.gitignore, README.md, helm-chart/dash0-operator/README.md
Also: remove the sections "Upgrading" and "Configuration" for now.
=> docs(chart): fix installation commands

helm-chart/dash0-operator/README.md, helm-chart/dash0-operator/templates/operator/verify-preconditions.yaml
Abort helm installation if:
- the authorization token secret is missing
- no ingress endpoint has been provided
=> feat(chart): abort installation if preconditions are not met

internal/webhook/dash0_webhook.go
Never return admission.Error from the webhook, if instrumentation fails, the new workload must be admitted anyway.
Also: Consistently log the outcome of processing the admission request.
=> fix(webhook): never block workload deployments

helm-chart/dash0-operator/Chart.yaml, helm-chart/dash0-operator/tests/operator/__snapshot__/cluster-role-bindings_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/cluster-roles_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/deployment_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/pre-delete-hook_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/role-binding_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/role_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/service-account_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/service_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/webhook_test.yaml.snap, images/instrumentation/Dockerfile, images/instrumentation/copy-instrumentation.sh, internal/webhook/dash0_webhook_test.go, internal/workloads/workload_modifier.go, internal/workloads/workload_modifier_test.go, test/e2e/e2e_test.go, test/util/resources.go, test/util/verification.go
to avoid conflicts with application containers actually using the /opt/dash0 folder.
=> fix: put instrumentation files in /__dash0__ instead of /opt/dash0

test/e2e/e2e_helpers.go
The end-to-end tests were flaky, sometimes failing the Eventually in sendRequestAndVerifySpans with a failed http request, although visibly no HTTP requests were executed for a long time. The assumption is that one of the http requests got stuck due to the missing timeout.
Plus: add more detailed output for end-to-end test http requests
=> test(e2e): set timeout on http requests to app under monitoring

CONTRIBUTING.md
=> docs(contributing): add missing build_image flags

CONTRIBUTING.md, test-resources/bin/util
=> chore(test-resources): remove BUILD_... image switches from scripts

helm-chart/dash0-operator/README.md
- explain dash0.com/enable=false in more detail
- list supported workload types
- new section for configuring metrics collection
- add note on CPU arch conflicts on Apple Silicon
=> docs: improve documentation

test/e2e/e2e_test.go
follow up to 41f3cd1
[skip ci]
=> test(e2e): more restructuring

.github/dependabot.yml
=> ci: fix path in dependabot.yaml

helm-chart/dash0-operator/templates/_helpers.tpl, helm-chart/dash0-operator/templates/operator/deployment-and-webhooks.yaml, helm-chart/dash0-operator/tests/operator/__snapshot__/deployment-and-webhooks_test.yaml.snap, helm-chart/dash0-operator/tests/operator/__snapshot__/pre-delete-hook_test.yaml.snap, internal/backendconnection/otelcolresources/desired_state.go, internal/util/zap/mru.go, internal/workloads/workload_modifier.go, test/e2e/e2e_test.go, test/e2e/operator.go
use consistent security contexts for all pods and containers
=> chore(chart, collectors): align pod & container security contexts

test/e2e/collector.go, test/e2e/e2e_test.go
The issue that reloading the collector config map/restarting the collector after changing the config map is gone, _very_ probably due to commit 0539d6b5d8a6616d4f54f5dc9c9156cc845c697e.
=> test(e2e): improve config reloading test

.github/actions/injector-and-instrumentation-tests/action.yaml, README.md, helm-chart/dash0-operator/README.md, images/instrumentation/test/node/base-images, images/instrumentation/test/node/test-cases/verify-distro-is-loaded/index.js, internal/startup/leader_election_aware_manager.go
Also, add Node.js 16 to instrumentation tests.
=>  test(instrumentation): fix verify-distro-is-loaded test

README.md, helm-chart/dash0-operator/README.md
=> docs: remove qualification as technical preview

internal/collectors/otelcolresources/desired_state.go, internal/workloads/workload_modifier.go
* Add CPU and memory requests to the dash0-instrumentation init container.
* Add CPU request to filelog-offset-volume-ownership init container.
=> chore: add resource requests to containers

helm-chart/dash0-operator/README.md
=> docs(chart): improve description of workload modifications

helm-chart/dash0-operator/README.md
Also, describe a solution with a filter rule to discard logs of individual workloads.
[skip ci]
=> docs(chart): dash.com/enable=false does not disable log collection

Makefile, internal/controller/perses_dashboards_controller.go, test-resources/bin/perses-crd-version-check.sh, test-resources/bin/third-party-crd-version-check-util, test-resources/bin/util, test-resources/customresources/persesdashboard/persesdashboard.yaml, test/util/crds/perses.dev_persesdashboards.yaml
Allow both the old and the new CRD format.
=> feat(dashboards): prepare for upcoming Perses CRD change

helm-chart/dash0-operator/templates/operator/cluster-roles.yaml, helm-chart/dash0-operator/tests/operator/__snapshot__/cluster-roles_test.yaml.snap, internal/startup/auto_operator_configuration_handler.go
corev1.Endpoints is deprecated
=> chore(startup): use discoveryv1.EndpointSlice instead of corev1.Endpoints

test-resources/otlp-sink/otlp-sink.yaml
=> test: update otlp-sink collector version

.github/dependabot.yml
=> ci(dependabot): tweak dependabot schedule
