dash0hq/dash0-operator

- config/default/manager_auth_proxy_patch.yaml
- helm-chart/dash0-operator/Chart.lock
- helm-chart/dash0-operator/Chart.yaml
- helm-chart/dash0-operator/README.md
- helm-chart/dash0-operator/templates/operator/deployment.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/deployment_test.yaml.snap
Apparently this image is no longer regularly published to gcr.io/kubebuilder/kube-rbac-proxy. Instead, the official repository for it is quay.io/brancz/kube-rbac-proxy.
> chore(deps): update kube-rbac-proxy + otel-collector chart

- helm-chart/dash0-operator/templates/operator/verify-preconditions.yaml
- helm-chart/dash0-operator/values.yaml
- test/e2e/e2e_helpers.go
This is required to enable the e2e tests to use the Helm chart, as the e2e tests deliberately do not install a secret and set the otlp exporter to null.
> chore(chart): allow disabling secret and otlp endpoint checks

- helm-chart/dash0-operator/README.md
- helm-chart/dash0-operator/templates/_helpers.tpl
- helm-chart/dash0-operator/templates/operator/deployment.yaml
- helm-chart/dash0-operator/templates/operator/verify-preconditions.yaml
- helm-chart/dash0-operator/tests/operator/deployment_test.yaml
- helm-chart/dash0-operator/values.yaml
Instead of installing a collector together with the operator. This option should only be used in very specific circumstances.
> feat(chart): support sending data to an existing collector instance

- images/instrumentation/node.js/build.sh
Actually, there is no need at all to do a local npm install before building the image.
> chore(instrumentation image): use Node distro version from package.json

- config/webhook/manifests.yaml
- helm-chart/dash0-operator/templates/operator/webhook.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/webhook_test.yaml.snap
- internal/controller/dash0_controller.go
- internal/util/labels.go
- internal/webhook/dash0_webhook.go
- internal/webhook/dash0_webhook_test.go
- internal/workloads/workload_modifier.go
- internal/workloads/workload_modifier_test.go
- test-resources/node.js/express/daemonset.opt-out.yaml
- test/e2e/e2e_helpers.go
- test/e2e/e2e_test.go
- test/util/resources.go
- test/util/verification.go
Also, instrument workloads via update request when the workload had opted out previously and is no longer opting out.
> feat(webhook): uninstrument workloads when opt-out label is added

- cmd/main.go
- config/rbac/role.yaml
- helm-chart/bin/publish.sh
- helm-chart/dash0-operator/README.md
- helm-chart/dash0-operator/templates/operator/cluster-roles.yaml
- helm-chart/dash0-operator/templates/operator/custom-resource-definition.yaml
- helm-chart/dash0-operator/templates/operator/deployment.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/cluster-roles_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/__snapshot__/custom-resource-definition_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/deployment_test.yaml
- helm-chart/dash0-operator/values.yaml
- internal/controller/dash0_controller.go
- internal/controller/dash0_controller_test.go
- test/e2e/e2e_helpers.go
- test/e2e/e2e_test.go
- test/util/verification.go
Run the instrumentation logic directly at process startup, for all
namespaces where a Dash0 resource exists, independently of reconcile
requests for the Dash0 resources. This main intention is to update the
instrumentation modifications for instrumented workloads immediately
when the operator controller image is updated (for example via helm
upgrade).
> feat(controller): apply and update instrumentation at startup

- cmd/main.go
- internal/backendconnection/otelcolresources/otelcol_resources_suite_test.go
- internal/dash0/controller/dash0_controller.go
- internal/dash0/controller/dash0_controller_suite_test.go
- internal/dash0/controller/dash0_controller_test.go
- internal/dash0/instrumentation/instrumentable_workloads.go
- internal/dash0/instrumentation/instrumentation_suite_test.go
- internal/dash0/instrumentation/instrumenter.go
- internal/dash0/instrumentation/instrumenter_test.go
- internal/dash0/util/controller.go
- internal/dash0/util/types.go
- internal/dash0/util/util_suite_test.go
- internal/dash0/webhook/attach_dangling_events_test.go
- internal/dash0/webhook/dash0_webhook_test.go
- internal/dash0/webhook/webhook_suite_test.go
- internal/dash0/workloads/workload_modifier_test.go
- internal/dash0/workloads/workloads_suite_test.go
- test/e2e/run_command.go
- test/util/constants.go
- test/util/resources.go
- test/util/verification.go
Extract the controller's instrumentation logic into a separate module, called instrumentation/instrumenter. This will facilitate running the InstrumentAtStartup task with a separate client and ultimately move it into executeStartupTasks, getting rid of the arbitrary (and potentially problematic) 10 second wait.
> refactor(controller, instrumenter): extract instrumentation logic

- .github/workflows/ci.yaml
- test/e2e/e2e_test.go
We would actually need to compare to the commit  of the last _successful_ build, not just to the last commit. Otherwise it will skip builds although the latest code has not been built yet.
> ci: remove changed files check

- CONTRIBUTING.md
- Makefile
- helm-chart/dash0-operator/README.md
- test/e2e/container_images.go
- test/e2e/e2e_test.go
- test/e2e/operator.go
This is no longer necessary, as no value from .env is used in the Makefile since #cbd57b53a3.
> test(e2e): remove BUILD_... image switches

- test-resources/bin/test-cleanup.sh
- test-resources/bin/test-roundtrip-01-aum-operator-cr.sh
- test-resources/bin/test-roundtrip-02-operator-cr-aum.sh
- test-resources/bin/util
* add util functions to deploy custom resources
* clean up first, then create test namespace
* delete old resources in this order now
- applications under monitoring
- custom resources (monitoring and operator configuration)
- delete test namespace
- uninstall operator helm chart
- delete Dash0 auth token secret
- delete dash0-system namespace
- delete CRDs (directly, instead of via make uninstall)
- delete other cluster-scope resources in case they have been left over
* call helm uninstall directly
> chore(test-resources): refactor test scripts and cleanup script

- internal/backendconnection/otelcolresources/desired_state.go
- internal/backendconnection/otelcolresources/desired_state_test.go
- internal/backendconnection/otelcolresources/otelcol_resources.go
For clusters managed by ArgoCD, we need to prevent ArgoCD to prune
Kubernetes resources necessary for the OTel collector managed by the
operator. If pruning is enabled in ArgoCD, it will automatically delete
resources which have no owner reference. This applies to all
cluster-scoped resources which the operator creates (since
cluster-scoped resource cannot be owned by namespace-scoped resources).
In particular, this affects the cluster role & cluster role binding.
References:
* https://github.com/argoproj/argo-cd/issues/4764#issuecomment-722661940
this indicates that only top level resources are pruned (which is
basically the same as resources without an owner reference).
* The docs for preventing this on a resource level are here: …
> fix(backendconnection): add annotation to prevent ArgoCD pruning

- test/e2e/dash0_monitoring_resource.go
- test/e2e/e2e_test.go
This test broke in commit 6b4da302a849e8c81e00d61e17b9826c977d5f86, when the export in the monitoring resource for e2e test was changed from an http exporter to a dash0 exporter.
> test(e2e): fix test case for updating the collector configuration

- internal/dash0/controller/perses_dashboards_controller.go
The dashboard origin is already specified via the URL, there is no more need to add it to the dashboard payload.
> chore(dashboards): do not duplicate origin in payload

- internal/dash0/controller/perses_dashboards_controller.go
- internal/dash0/controller/perses_dashboards_controller_test.go
This avoids running the Perses dashboard model validation on the side of the operator, which would for example create issues when using Dash0 specific variable types (e.g. Dash0FilterVariables).
> fix(dashboards): do not unmarshal Perses dashboard resources

- internal/dash0/controller/operator_configuration_controller.go
- internal/dash0/controller/perses_dashboards_controller.go
- internal/dash0/controller/perses_dashboards_controller_test.go
- internal/dash0/startup/auto_operator_configuration_handler.go
- test-resources/bin/test-scenario-01-aum-operator-cr.sh
- test-resources/bin/test-scenario-02-operator-cr-aum.sh
That is:
* do not do anything if there is no auth token
* watch for the Perses dashboard CRD, potentially starting the watch for dashboard resources once it is created
* wait until an API endpoint configuration is available
> fix(dashboards): start watching dashboards when all conditions are met

- images/configreloader/src/configreloader.go
- test/e2e/collector.go
- test/e2e/e2e_test.go
- test/e2e/run_command.go
It sometimes takes a while for a config map change to actually be seen from within the pod/container (in particular the config-reloader). Might be a Docker Desktop thing. Either way, increasing the timeout makes the test more stable.
> test(e2e): fix config reloader e2e test

- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
Refined log messages from Kubernetes pods/containers were only available in the `log` attribute but were never copied into the log record body.
This PR adds the necessary `move` operator to move the cleaned up log message from `attributes.log` to `body`.
The operator is also used in the recommended OpenTelemetry Collector configuration for Kubernetes:
https://github.com/open-telemetry/opentelemetry.io/blob/2024.09/content/en/docs/kubernetes/collector/components.md?plain=1#L328-L330
Refs https://github.com/open-telemetry/opentelemetry.io/pull/3073
> fix: move attributes.log to body field for filelog/monitored_pods

- .github/workflows/ci.yaml
- README.md
- api/dash0monitoring/v1alpha1/dash0monitoring_types.go
- api/dash0monitoring/v1alpha1/operator_configuration_types.go
- config/crd/bases/operator.dash0.com_dash0monitorings.yaml
- config/crd/bases/operator.dash0.com_dash0operatorconfigurations.yaml
- helm-chart/dash0-operator/Chart.yaml
- helm-chart/dash0-operator/README.md
- helm-chart/dash0-operator/templates/NOTES.txt
- helm-chart/dash0-operator/templates/operator/custom-resource-definition-monitoring.yaml
- helm-chart/dash0-operator/templates/operator/custom-resource-definition-operator-configuration.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/custom-resource-definition-monitoring_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/__snapshot__/custom-resource-definition-operator-configuration_test.yaml.snap
- helm-chart/dash0-operator/values.yaml
- images/collector/src/builder/config.yaml
- internal/predelete/operator_pre_delete_handler_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_test.go
1. Add overview of the capailities in main README
2. Document prometheus.io/* annotation support in Helm chart docs
3. Harmonize naming to "Dash0 operator", as "Dash0 Kubernetes operator" is redundant in the context people are looking the operator up
> docs: various changes

- .github/workflows/ci.yaml
- internal/controller/perses_dashboards_controller.go
- internal/controller/perses_dashboards_controller_test.go
- internal/controller/prometheus_rules_controller.go
- internal/controller/prometheus_rules_controller_test.go
- internal/controller/third_party_crd_common.go
- test-resources/customresources/persesdashboard/persesdashboard.yaml
Fixed by moving back from using the actual type
(&persesv1alpha1.PersesDashboard{}, &prometheusv1.PrometheusRule{}) when creating the watch, to watching for *unstructured.Unstructured with group/version/kind attributes. We cannot watch for the specific third-party resource type directly since when we do that, the validation for the resource in question would be triggered before the resource is handed over to the event handler.
This validation potentially fails for dashboards, because Dash0 dashboards allow variable types (like Dash0FilterVariable) that plain vanilla Perses dashboards do not support, and the following validation error is triggered:
reflector.go:158] "Unhandled Error"
err="pkg/mod/k8s.io/client-go@v0.31.2/tools/cache/reflector.go:243: Failed to watch …
> fix(dashboards): avoid validation error for Dash0FilterVariable

- CONTRIBUTING.md
- cmd/main.go
- internal/backendconnection/backendconnection_manager.go
- internal/backendconnection/backendconnection_manager_test.go
- internal/backendconnection/otelcolresources/desired_state.go
- internal/backendconnection/otelcolresources/otelcol_resources.go
- internal/backendconnection/otelcolresources/otelcol_resources_test.go
- internal/controller/monitoring_controller.go
- internal/controller/monitoring_controller_test.go
- internal/controller/operator_configuration_controller.go
- internal/controller/operator_configuration_controller_test.go
- test-resources/bin/util
- test/e2e/dash0_operator_configuration_resource.go
- test/e2e/e2e_test.go
- test/util/collector.go
- test/util/monitoring_resource.go
- test/util/operator_resource.go
Trigger a reconciliation of the OTel collector resources when the
operator configuration resource is changed.
Also: Delete a subset of collector resources if operator configuration
resource has changed in a way so that some resources are no longer
required - in particular, when switching from
KubernetesInfrastructureMetricsCollectionEnabled=true to false, delete
the collector deployment for the cluster metrics.
> fix(controller): reconcile collector from operator configuration

- cmd/main.go
- internal/startup/auto_operator_configuration_handler.go
- internal/startup/auto_operator_configuration_handler_test.go
- internal/webhooks/monitoring_validation_webhook_test.go
- internal/webhooks/operator_configuration_validation_webhook.go
- internal/webhooks/operator_configuration_validation_webhook_test.go
If an operator configuration resource has been requested via Helm values, and there is already an existing operator configuration resource in the cluster, update it according to the values provided via Helm instead of ignoring the Helm values.
> feat(chart): update operator configuration resource via helm chart

- internal/controller/monitoring_controller_test.go
- internal/controller/operator_configuration_controller.go
- internal/instrumentation/instrumenter.go
- internal/instrumentation/instrumenter_test.go
- internal/util/constants.go
- internal/webhooks/instrumentation_webhook_test.go
- internal/workloads/workload_modifier_test.go
- test-resources/bin/test-scenario-03-update-operator.sh
- test-resources/bin/util
- test/util/resources.go
- test/util/verification.go
Set the field manager to dash0-operator when instrumenting workloads. This makes it easier to identify which managed fields have been written by the Dash0 operator.
> fix(controller): use clearly identifiable field manager

- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
This PR tunes **kubeletstats** metrics. It enables useful metrics and disables deprecated metrics.
Related documentation https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md
> Tune kubeletstats metrics - enable useful / disable deprecated metrics

- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
Re-enable all metrics that have been disabled in 136bb8f5ca, only explicitly disable the deprecated metrics. The metrics that are off by default, and have been explicitly enabled in 136bb8f5ca are still enabled.
> feat(metrics): tune kubeletstats metrics (again)

- helm-chart/dash0-operator/README.md
- images/collector/src/image/entrypoint.sh
- internal/backendconnection/otelcolresources/collector_config_maps_test.go
- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
- internal/backendconnection/otelcolresources/desired_state.go
The Kubelet stats endpoint on Minikube, Docker Desktop and Kind appears to use self-signed certificates that are not signed by the cluster's certificate authority. This means that they are invalid for the Daemonset's collector, preventing kubelet-based metrics from being collected, and degrading the first user experience of the operator for end users that try it in a local cluster.
This change works around it by disabling TLS veritification for the kubeletstats receiver if the collector is running on a node named "minikube" or "docker-desktop", and documenting ways to solve the issue for Kind or `minikube -p <profile_name>`.
> feat: make kubeletstatsreceiver work ootb on Minikube and Docker Desktop

- internal/backendconnection/otelcolresources/desired_state.go
- internal/backendconnection/otelcolresources/desired_state_test.go
This is a follow-up to 9b3360f41933bc60ef793e230ee27c2b8b6703eb. In addition to adding the annotation
argocd.argoproj.io/sync-options: Prune=false, we now also set argocd.argoproj.io/compare-options: IgnoreExtraneous.
This should exclude the resources managed by the operator ArgoCD sync completely.
See
https://argo-cd.readthedocs.io/en/stable/user-guide/compare-options/#ignoring-resources-that-are-extraneous
> fix(backendconnection): add another annotation for ArgoCD

- helm-chart/dash0-operator/README.md
- helm-chart/dash0-operator/templates/operator/deployment-and-webhooks.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/deployment-and-webhooks_test.yaml.snap
- internal/backendconnection/otelcolresources/desired_state.go
This PR adds a default node-antiaffinity that will prevents all pods sc heduled by the operator (manager, otelcol deployment, otelcol daemonset) to be scheduled on nodes with the `dash0.com/enable=false` label
> feat: add default node anti-affinity for all operator pods

- internal/backendconnection/otelcolresources/deployment.config.yaml.template
- test/e2e/k8s_cluster_receiver_metrics.txt
In particular, the following metrics were dropped:
* k8s.container.restarts
* k8s.replicaset.desired
* k8s.replicaset.available
> chore(metrics): disable noisy cluster metrics that do not add value

- internal/backendconnection/otelcolresources/desired_state.go
- internal/instrumentation/instrumentable_workloads.go
- internal/instrumentation/instrumenter.go
- internal/instrumentation/instrumenter_test.go
- internal/util/constants.go
- internal/util/k8s_events.go
- internal/util/labels.go
- internal/util/types.go
- internal/util/workload_types.go
- internal/webhooks/instrumentation_webhook.go
- internal/webhooks/instrumentation_webhook_test.go
- internal/workloads/workload_modifier.go
- internal/workloads/workload_modifier_test.go
- test/util/collector.go
- test/util/resources.go
- test/util/verification.go
Unless it is a known owner reference type which is instrumented at the higher workload type level (like apps/v1 Deployment etc.).
ENG-3782
> fix(workloads): also instrument standalone pods with owner reference

- .github/workflows/ci.yaml
This will be very handy for release builds, where the very same commit
has usually been build successfully when building the main branch.
> ci: skip steps if successful build for the same commit exists

- helm-chart/dash0-operator/README.md
- internal/backendconnection/backend_connection_controller.go
- internal/backendconnection/backendconnection_manager.go
- internal/backendconnection/backendconnection_manager_test.go
- internal/backendconnection/otelcolresources/collector_config_maps.go
- internal/backendconnection/otelcolresources/otelcol_resources.go
- internal/backendconnection/otelcolresources/otelcol_resources_test.go
- internal/controller/monitoring_controller.go
- internal/controller/monitoring_controller_test.go
- internal/controller/operator_configuration_controller_test.go
- internal/predelete/operator_pre_delete_handler_test.go
- test/e2e/e2e_test.go
- test/e2e/match_results.go
- test/e2e/metrics.go
- test/e2e/setup_teardown.go
- test/e2e/spans.go
- test/util/collector.go
- test/util/constants.go
- test/util/monitoring_resource.go
- test/util/operator_resource.go
Deploy the Dash0 OpenTelemetry collectors as soon as an operator configuration resource with an export is available. In particular, the slightly arbitrary requirement of having at least one Dash0 monitoring resource monitoring a namespace for getting _any_ telemetry from a cluster is removed with this. This enables collecting non-namespace scoped metrics as soon as export settings are available.
> feat(backendconnection): deploy collectors via operator configuration

- cmd/main.go
- images/collector/src/builder/config.yaml
- internal/backendconnection/otelcolresources/collector_config_maps.go
- internal/backendconnection/otelcolresources/collector_config_maps_test.go
- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
- internal/backendconnection/otelcolresources/desired_state.go
- internal/backendconnection/otelcolresources/desired_state_test.go
- internal/backendconnection/otelcolresources/otelcol_resources.go
Use the hostmetrics receiver to collect host metrics from the underlying node:
- system.cpu.utilization
- system.filesystem.utilization
- system.memory.utilization
> feat(metrics): collect host metrics

- helm-chart/dash0-operator/templates/operator/deployment-and-webhooks.yaml
Setting the `operator.webhookPort` value when installing the operator chart could result in calls failing calls to the Mutating and Validation webhooks of the operator.
This, in turn, could prevent, for example, the creation of `Dash0OperatorConfiguration` or `Dash0Monitoring` resources.
> fix: propagate custom webhook service ports in WebhookConfigurations

- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
This is now effectively a required parameter, see: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36873#issuecomment-2666200790
> fix(collectors): add fallback_scrape_protocol

- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
According to
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38018/files#r1959868040 the proper default for the fallback protocol is PrometheusText0.0.4.
This is a follow up to fb0c55d7f43509ada73e640e01ee5b2a4d064ff4.
> fix(collectors): change fallback_scrape_protocol to PrometheusText0.0.4

- internal/backendconnection/otelcolresources/daemonset.config.yaml.template
- internal/backendconnection/otelcolresources/deployment.config.yaml.template
- test/e2e/collector.go
- test/e2e/e2e_test.go
- test/e2e/run_command.go
If a config map contains a space characters followed by a line break, it is rendered in the edit view of k9s as one long unformatted string with literal \n characters instead of line breaks. The text/template templates for the daemonset and deployment collector configs produced this particular pattern, triggering that effect. This change removes this pattern and adds an e2e test making sure it is not accidentally reintroduced.
See
https://github.com/kubernetes/kubernetes/issues/36222#issuecomment-2006988070
> chore(collectors): make config maps render nicely in k9s edit view

- images/pkg/common/otel.go
- internal/controller/operator_configuration_controller.go
- internal/selfmonitoringapiaccess/self_monitoring_and_api_access.go
- test-resources/bin/util
- test-resources/customresources/dash0operatorconfiguration/dash0operatorconfiguration.otlpsink.yaml
- test/e2e/operator.go
This fixes the issue that self-monitoring telemetry could not be exported from the operator manager when the configured export endpoint included a scheme (http://, https://).
> fix(self-monitoring): fix self-monitoring for endpoints with scheme

- cmd/main.go
- helm-chart/dash0-operator/README.md
- internal/controller/operator_configuration_controller.go
- internal/controller/operator_configuration_controller_test.go
- internal/controller/third_party_crd_common.go
- internal/startup/auto_operator_configuration_handler.go
- internal/util/retry.go
- test/e2e/e2e_test.go
...with values provided via Helm.
Previously, when instructed to create/update the operator configuration
resource via Helm, the operator manager would update any operator
configuration resource it finds with the provided value. This would
likely lead to unexpected results if people transition from a manually
configured operator configuration resource to a Helm-managed values.
Now the operator will refuse to overwrite the existing resource in this
scenario and log an error.
Also: Describe the behavior around creating the operator configuration
resource via Helm in more detail in the docs.
> fix: do not overwrite manually created operator configuration resource

- internal/instrumentation/instrumenter.go
- internal/util/labels.go
- internal/workloads/workload_modifier.go
- internal/workloads/workload_modifier_test.go
- test-resources/bin/test-cleanup.sh
- test/util/resources.go
- test/util/verification.go
The local volume dash0-instrumentation will block pod eviction by the Kubernetes cluster auto-scaler, and in turn block node scale down and optimal bin packing of pods on nodes.
Adding the annotation
cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes with the dash0-instrumentation volume name as a value prevents that, i.e. it tells the autoscaler that it is okay to evict the pod even though this local volume is present.
> feat(workloads): do not block cluster autoscaler pod eviction

- helm-chart/dash0-operator/README.md
Adding the annotation
"cluster-autoscaler.kubernetes.io/safe-to-evict": "true" is no longer necessary as of release 0.51.0.
[skip CI]
> docs(chart): remove section on safe-to-evict annotation

- cmd/main.go
- internal/controller/perses_dashboards_controller.go
- internal/controller/perses_dashboards_controller_test.go
- internal/controller/prometheus_rules_controller.go
- internal/controller/prometheus_rules_controller_test.go
- internal/controller/third_party_crd_common.go
- internal/selfmonitoringapiaccess/otel_init_wait.go
- internal/util/cluster.go
- internal/util/constants.go
Delete individual check rules in Dash0 via the API when the corresponding group or rule has been deleted (or renamed) in the PrometheusRules Kubernetes resource.
> fix(checkrules): delete obsolete check rules in Dash0

- images/collector/src/builder/config.yaml
To include the fix for
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39414 (excessive printing of file names).
> fix(collectors): bump filelog receiver to 0.124.1

- .gitignore
- cmd/main.go
- internal/controller/perses_dashboards_controller.go
- internal/controller/perses_dashboards_controller_test.go
- internal/controller/prometheus_rules_controller.go
- internal/controller/prometheus_rules_controller_test.go
- internal/controller/third_party_crd_common.go
- internal/startup/instrument_at_startup.go
- internal/startup/leader_election_aware_manager.go
- internal/webhooks/instrumentation_webhook.go
- test-resources/bin/util
- test/e2e/applications_under_test.go
- test/e2e/operator.go
- test/e2e/run_command.go
- test/util/third_party_resource.go
If the reason the third-party resource reconcilers cannot start watching
their target custom resource type yet is that this replica is not the
leader, then include that reasoning in the log message.
> chore(checkrules,dashboards): improve logs for non-leader replicas

- helm-chart/dash0-operator/templates/operator/deployment-and-webhooks.yaml
Specifically, exclude the namespaces kube-system and kube-node-lease from the injector webhook, requests for these namespaces will not be routed to the webhook, and hence workloads in those namespaces will not be instrumented by the injector webhook.
> fix(chart): exclude Kubernetes system namespaces from injector webhook

- internal/webhooks/monitoring_validation_webhook.go
- internal/webhooks/monitoring_validation_webhook_test.go
- test/util/monitoring_resource.go
Deploying a Dash0 monitoring resource to a system namespace (kube-system, kube-node-lease) is now only deployed with InstrumentWorkloads: none.
> fix(webhook): disallow instrumenting workloads in system namespaces

- helm-chart/dash0-operator/README.md
- test-resources/bin/util
https://github.com/perses/perses-operator/pull/128 changed the CRD format, so the previous recommendation to install the CRD from their main branch would breaks things.
> docs(chart): suggest a fixed CRD version for Perses dashboards

- Makefile
- helm-chart/dash0-operator/README.md
- internal/webhooks/instrumentation_webhook_test.go
- internal/workloads/workload_modifier.go
- internal/workloads/workload_modifier_test.go
- test/util/resources.go
- test/util/verification.go
The operator already adds/replaces OTEL_EXPORTER_OTLP_ENDPOINT when instrumenting workloads, to the collector URL that accepts http/protobuf traffic. If OTEL_EXPORTER_OTLP_ENDPOINT is set but the OpenTelemetry SDK in the instrumented workload defaults to gRPC, exporting telemetry will not work. Hence, the operator now also sets OTEL_EXPORTER_OTLP_PROTOCOL to http/protobuf explicitly.
> feat(workloads): set OTEL_EXPORTER_OTLP_PROTOCOL

- helm-chart/dash0-operator/tests/operator/__snapshot__/extra-config-map_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/extra-config-map_test.yaml
- helm-chart/dash0-operator/values.yaml
- internal/util/extraconfig.go
- internal/util/extraconfig_test.go
This removes the default resource requests (cpu: 100m, memory: 150Mi)
for the Dash0 instrumentation init container.
Turns out, default resource requests for an init container that is
added to all pods has quite negative side effects: Contrary to what
one might intuitively assume, requested resources are _not_ freed up
after the init container has completed. See the discussion in
https://github.com/kubernetes/kubernetes/issues/124282.
This can make setting resource requests expensive, and can lead to
CPU/memory being needlessly reserved by the scheduler for the already
finished init container, although it will actually never be used again.
BREAKING CHANGE: This is a breaking change if you actually want
resource requests for the Dash0 instrumentation init container _and_
you are currently …
> fix(chart): remove default resource requests for init container

- test/e2e/e2e_test.go
...now that exporting internal telemetry to a non-tls endpoints via gRPC finally works, due to
https://github.com/open-telemetry/opentelemetry-collector/issues/12701 being fixed via
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6984 and
https://github.com/open-telemetry/opentelemetry-collector/pull/13098.
[skip ci]
> test(e2e): enable collector logs test case

- internal/collectors/otelcolresources/collector_config_maps_test.go
- internal/selfmonitoringapiaccess/self_monitoring_and_api_access.go
- internal/selfmonitoringapiaccess/self_monitoring_and_api_access_test.go
Until release v0.127.0/v1.33.0 of the OpenTelemetry collector, specifying the export endpoint for the collector's internal telemetry/self-monitoring
(that is,
service.telemetry.logs.processors[batch].exporter.otlp.endpoint) as "ingress.eu-west-1.aws.dash0-dev.com:4317" (without a scheme prefix) worked perfectly fine. Starting with collector release v0.128.0/v1.34.0 this stopped working and the endpoint now needs a scheme prefix.
The issue would manifest as logs like the following in the collector logs (both daemonset and deployment collector pods):
```
warn grpc@v1.73.0/clientconn.go:1414 [core] [Channel #1 SubChannel #5]grpc:
addrConn.createTransport failed to connect to {Addr: "34.240.90.89:4317",
ServerName: "ingress.eu-west-1.aws.dash0-dev.com:4317",
BalancerAttributes: …
```
> fix(collectors): prepend scheme to self-monitoring logs endpoint

- Makefile
- test/e2e/run_command.go
This is the default value since Go 1.16.
> chore: remove GO111MODULE=on

- images/instrumentation/Dockerfile
- images/instrumentation/injector/src/node_js.zig
- images/instrumentation/injector/test/scripts/create-inaccessible-sdk-dummy-files.sh
- images/instrumentation/injector/test/scripts/create-sdk-dummy-files.sh
- images/instrumentation/injector/test/scripts/default.tests
- images/instrumentation/node.js/.gitignore
- images/instrumentation/node.js/build.sh
- images/instrumentation/node.js/package-lock.json
- images/instrumentation/node.js/package.json
- images/instrumentation/test/node/test-cases/node-options-already-set/index.js
- images/instrumentation/test/node/test-cases/node-options-unset/index.js
- images/instrumentation/test/node/test-cases/verify-distro-is-loaded/index.js
The Dash0 Node.js OpenTelemetry is now under a new organization/scope, moving from @dash0hq/opentelemetry to @dash0/opentelemetry.
> chore(instrumentation): move to Node.js package @dash0/opentelemetry

- internal/collectors/otelcolresources/daemonset.config.yaml.template
- test/e2e/kubeletstats_receiver_metrics.txt
Add the following Kubernetes volume metrics for volumes in monitored
namespaces:
- k8s.volume.available
- k8s.volume.capacity
If you do not want to collect these metrics, they can be disabled via
filters in the Dash0 monitoring resource or via spam filters in Dash0.
Inode-related metrics are disabled at the moment, that is, the following
metrics are not collected:
- k8s.volume.inodes
- k8s.volume.inodes.free
- k8s.volume.inodes.used
> feat(collectors): enable Kubernetes volume metrics

- images/instrumentation/Dockerfile
- images/instrumentation/injector/src/jvm.zig
- images/instrumentation/injector/src/root.zig
- images/instrumentation/injector/src/test_util.zig
- images/instrumentation/injector/test/README.md
- images/instrumentation/injector/test/docker/Dockerfile-test
- images/instrumentation/injector/test/scripts/default.tests
- images/instrumentation/injector/test/scripts/run-tests-for-container.sh
- images/instrumentation/injector/test/scripts/run-tests-within-container.sh
- images/instrumentation/injector/test/scripts/test-all.sh
- images/instrumentation/injector/watch-zig-build.sh
- images/instrumentation/injector/watch-zig-test.sh
- images/instrumentation/injector/zig-build.sh
- images/instrumentation/injector/zig-test.sh
- images/instrumentation/test/.gitignore
- images/instrumentation/test/cleanup.sh
- images/instrumentation/test/jvm/test-cases/otel-resource-attributes-env-var-already-set/Main.java
- internal/startup/auto_operator_configuration_handler.go
- internal/startup/auto_operator_configuration_handler_test.go
OpenTelemetry resource attributes can be set for the JVM via the
OTEL_RESOURCE_ATTRIBUTES environment variable or by adding the system
property -Dotel.resource.attributes to the JAVA_TOOL_OPTIONS environment
variable. The Java OTel SDK will ignore OTEL_RESOURCE_ATTRIBUTES if
-Dotel.resource.attributes is set.
The Dash0 injector will add -Dotel.resource.attributes to
JAVA_TOOL_OPTIONS to add useful Kubernetes-related resource attributes
like pod uid, pod name etc. This can accidentally discard user-provided
values from OTEL_RESOURCE_ATTRIBUTES.
This fix makes the injector merge the values from
OTEL_RESOURCE_ATTRIBUTES into -Dotel.resource.attributes in situations
where this is appropriate.
> fix(injector): merge OTEL_RESOURCE_ATTRIBUTES into JAVA_TOOL_OPTIONS

- helm-chart/dash0-operator/README.md
Document that the persistent volume claim for the file offset must be set in access mode `ReadWriteMany`
> Update PVC documentation with the access mode

- images/instrumentation/Dockerfile
The `zig` package in the alpine edge branch has recently been updated to `0.15.1` which caused issues with our build.
This PR updates the alpine image to 3.22 and removes the edge/community repository, so the version from the default community repo is used (which corresponds to `0.14.1`).
> chore(instrumentation): update alpine image, remove edge/community repo

- helm-chart/dash0-operator/README.md
The Open Policy Agent gatekeeper (and in turn AKS with the Azure Policy add-on enabled) have the same issue as the Kyverno admission controller, that is, they frequent ConfigMap updates of the operator cause high CPU usage for these components; making the use of a persistent volume for filelog offsets more or less mandatory.
> docs(chart): recommend a filelog offset volume for OPA and AKS

- test-resources/dotnet/daemonset.yaml
- test-resources/dotnet/deployment.yaml
- test-resources/dotnet/pod.yaml
- test-resources/dotnet/replicaset.yaml
- test-resources/dotnet/statefulset.yaml
- test-resources/jvm/spring-boot/daemonset.yaml
- test-resources/jvm/spring-boot/deployment.yaml
- test-resources/jvm/spring-boot/pod.yaml
- test-resources/jvm/spring-boot/replicaset.yaml
- test-resources/jvm/spring-boot/statefulset.yaml
- test-resources/node.js/express/daemonset.opt-out.yaml
- test-resources/node.js/express/daemonset.yaml
- test-resources/node.js/express/deployment.yaml
- test-resources/node.js/express/pod.yaml
- test-resources/node.js/express/replicaset.yaml
- test-resources/node.js/express/statefulset.yaml
- test-resources/python/flask/daemonset.yaml
- test-resources/python/flask/deployment.yaml
- test-resources/python/flask/pod.yaml
- test-resources/python/flask/replicaset.yaml
- test-resources/python/flask/statefulset.yaml
- test/e2e/e2e_test.go
- test/e2e/kind.go
- test/e2e/otlp_sink.go
- test/e2e/util.go
When running the e2e tests on kind where http requests from the test suite to the apps under test is routed via an K8s ingress, and when running multiple apps under test with the same workload type in parallel, the ingress path definitions would conflict, i.e. both the Node.js deployment and the JVM deployment would register /deployment(/|$)(.*) as their path. Since some test cases run multiple apps in parallel, the path needs to be unique. Including the runtime of the app under test fixes this.
> test(e2e): fix ingress path for apps under test

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- Makefile
- helm-chart/dash0-operator/templates/_helpers.tpl
- helm-chart/dash0-operator/templates/operator/deployment-and-webhooks.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/deployment-and-webhooks_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/deployment-and-webhooks_test.yaml
- helm-chart/dash0-operator/values.yaml
- images/filelogoffsetvolumeownership/Dockerfile
- internal/collectors/collector_manager_test.go
- internal/collectors/otelcolresources/desired_state.go
- internal/collectors/otelcolresources/desired_state_test.go
- internal/collectors/otelcolresources/otelcol_resources.go
- internal/startup/operator_manager_startup.go
- internal/util/types.go
- test-resources/bin/util
- test/e2e/container_images.go
- test/e2e/e2e_test.go
- test/e2e/operator.go
- test/util/constants.go
When a host volume is used for storing filelog offsets, we attach an init container to set up the correct ownership in the volume. Previously, this was the busybox image directly from Dockerhub. This can cause issues with Dockerhub's pull rate limit. To avoid that, we build a custom image for this init container and make it configurable via Helm, consistent with all other container images used in the collector pods.
> feat(collectors): use custom image for filelog offset volume ownership

- .github/dependabot.yml
Small PR to add automatic version updates for Docker.
Note: I didn't add a config for Helm, since it only checks the chart dependencies and not the images used in the templates/manifests. Since we currently don't depend on any other charts, that check wouldn't provide any value.
> ci: add dependabot config for docker

- helm-chart/dash0-operator/templates/operator/post-install-hook.yaml
- helm-chart/dash0-operator/templates/operator/pre-delete-hook.yaml
- helm-chart/dash0-operator/tests/operator/__snapshot__/post-install-hook_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/__snapshot__/pre-delete-hook_test.yaml.snap
- helm-chart/dash0-operator/tests/operator/post-install-hook_test.yaml
- helm-chart/dash0-operator/tests/operator/pre-delete-hook_test.yaml
In particular, these are now also applied to the post-install and the pre-delete Helm hook jobs. Without the tolerations for example, the operator would be scheduled on tainted nodes, but the post-install hook pod not, so helm install --wait would wait forever.
> fix(chart): apply tolerations, priority class and affinity to hooks

- internal/collectors/otelcolresources/daemonset.config.yaml.template
- internal/collectors/otelcolresources/deployment.config.yaml.template
- test/e2e/k8s_cluster_receiver_metrics.txt
- test/e2e/kubeletstats_receiver_metrics.txt
New metrics:
- kubeletstats receiver:
- k8s.volume.inodes
- k8s.volume.inodes.free
- k8s.volume.inodes.used
- k8scluster receiver:
- k8s.container.restarts
- k8s.container.status.reason
> feat(collectors): enable inodes & container restarts metrics
